version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: adegaDB
    restart: unless-stopped
    ports:
      - "7474:7474" # Interface web (Neo4j Browser)
      
      - "7687:7687" # Porta de conexão do Driver do Express (Bolt)
    environment:
      # Credenciais de acesso
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      # Persistência de dados
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import