import type { RouteName } from '../navigation/types';

type TitlePart = string | { em: string };

const OFFLINE = '(Dados de exemplo offline.)';

export const copy = {
  navTitles: {
    Home: 'Cachaceiro Viajante — Roteiros de cachaça em Minas Gerais',
    Distilleries: 'Alambiques — Cachaceiro Viajante',
    RoutePlanner: 'Monte sua rota — Cachaceiro Viajante',
    Journal: 'Diário de bordo — Cachaceiro Viajante',
    About: 'Sobre — Cachaceiro Viajante',
    SignIn: 'Entrar — Cachaceiro Viajante',
    SignUp: 'Criar conta — Cachaceiro Viajante',
    SuggestPlace: 'Indicar alambique — Cachaceiro Viajante',
  } satisfies Record<RouteName, string>,

  chrome: {
    brandFooter: 'CACHACEIRO VIAJANTE · MINAS GERAIS',
    moderation: 'BEBA COM MODERAÇÃO · 18+',
  },

  footer: {
    brandText: 'O guia da cachaça mineira que monta o melhor roteiro entre os alambiques que você escolhe — menos estrada, mais prosa e bons goles pelo caminho.',
    flag: 'MINAS GERAIS · BRASIL',
    colophon: [
      '© 2026 CACHACEIRO VIAJANTE · UM ALMANAQUE DE ESTRADA EM NEO4J',
      'ALAMBIQUES · ESTRADAS · MINAS GERAIS',
      'BEBA COM MODERAÇÃO · 18+',
    ],
  },

  signIn: {
    docLabel: 'DOC. Nº 01 — IDENTIFICAÇÃO DO VIAJANTE',
    title: 'Bem-vindo de volta, viajante.',
    subtitle: 'Abra seu caderno: suas rotas, notas de campo e reputação moram no grafo.',
    identifier: 'E-mail ou usuário',
    identifierPlaceholder: 'maria@exemplo.com',
    password: 'Senha',
    passwordPlaceholder: '••••••••',
    submit: 'Entrar',
    submitting: 'Entrando…',
    switchText: 'Primeira viagem?',
    switchLink: 'Crie sua carteirinha de viajante →',
  },

  signUp: {
    docLabel: 'DOC. Nº 02 — REGISTRO DE NOVO VIAJANTE',
    title: 'Tire sua carteirinha de viajante.',
    subtitle: 'Uma carteirinha, todas as estradas: salve rotas, registre notas de campo e ganhe reputação pelo caminho.',
    mismatch: 'As senhas não conferem.',
    name: 'Nome completo',
    namePlaceholder: 'Maria da Estrada',
    username: 'Usuário',
    usernameHint: '3–24 CARACTERES · A–Z 0–9 _ . -',
    usernamePlaceholder: 'maria.estrada',
    email: 'E-mail',
    emailPlaceholder: 'maria@exemplo.com',
    password: 'Senha',
    passwordHint: 'MÍN. 6 CARACTERES',
    passwordPlaceholder: '••••••••',
    confirm: 'Confirmar senha',
    confirmPlaceholder: '••••••••',
    submit: 'Criar conta',
    submitting: 'Carimbando…',
    switchText: 'Já tem a carteirinha?',
    switchLink: 'Entrar →',
  },

  home: {
    kicker: (live: boolean) => `GUIA DE CAMPO DA CACHAÇA · MINAS GERAIS · ${live ? 'GRAFO AO VIVO' : 'DADOS DE EXEMPLO'}`,
    statLabels: ['ALAMBIQUES', 'CIDADES MINEIRAS', 'NOTAS DE CAMPO', 'REGIÕES'],
    ctaRoute: 'Montar minha rota',
    ctaExplore: 'Explorar alambiques',
    featTitle: 'Garrafas que valem a estrada.',
    featLink: (n: number) => `VER TODOS OS ${n} →`,
    steps: [
      { n: '01', t: 'Escolha os alambiques', p: 'Navegue pelo catálogo ou toque nos pinos do mapa real — cada alambique é um nó num grafo Neo4j de Minas Gerais.' },
      { n: '02', t: 'O grafo resolve', p: 'As distâncias vêm do motor espacial do banco; uma heurística de caixeiro-viajante acha a ordem que desperdiça menos estrada.' },
      { n: '03', t: 'Pé na estrada', p: 'Receba o roteiro trecho a trecho, desenhado sobre as rodovias reais do OpenStreetMap, com tempo de direção e paradas de prova.' },
    ],
    teaserP: 'Marque os alambiques que te tentam e o Cachaceiro Viajante calcula a ordem mais curta de visita em segundos — pronta pro para-brisa.',
    teaserCta: 'Abrir o planejador',
  },

  about: {
    title: ['Estradas como ', { em: 'relacionamentos.' }] as TitlePart[],
    lede: 'O Cachaceiro Viajante é um trabalho da disciplina de Banco de Dados II (UFOP) que trata uma viagem de cachaça do jeito que um banco de grafos trata o mundo: lugares são nós, estradas são relacionamentos, e o melhor roteiro é uma pergunta feita ao grafo.',
    modelTitle: 'O modelo.',
    modelSub: 'UM GRAFO, QUATRO RÓTULOS, COORDENADAS REAIS',
    figLeft: 'FIG. 03 — MODELO DE GRAFO DE PROPRIEDADES',
    archTitle: 'A arquitetura.',
    archSub: 'MONÓLITO MODULAR · CAMADAS MSC',
    stack: [
      { layer: 'Frontend', tech: 'Expo / React Native Web · TypeScript · Leaflet' },
      { layer: 'Backend', tech: 'Node.js · Express · autenticação JWT · camadas MSC' },
      { layer: 'Banco', tech: 'Neo4j 5 — grafo de propriedades + point.distance espacial' },
      { layer: 'Roteamento', tech: 'Heurísticas de TSP (vizinho mais próximo, 2-opt) · geometria viária OSRM' },
      { layer: 'Infra', tech: 'Docker / Podman compose · Makefile · demo em localhost' },
    ],
    rulesTitle: 'Regras da casa.',
    rulesSub: 'REGRAS DE NEGÓCIO QUE O GRAFO IMPÕE',
    rules: [
      { id: 'RN04', text: 'Qualquer viajante logado pode indicar um novo alambique, marcado por coordenadas no mapa.' },
      { id: 'RN05', text: 'Toda indicação entra em quarentena como EM VALIDAÇÃO até ser confirmada.' },
      { id: 'RN06', text: 'O catálogo permite incluir ou esconder paradas em quarentena.' },
      { id: 'RN07', text: 'Os pesos das arestas são recalculados a cada requisição a partir dos dados espaciais do grafo.' },
      { id: 'RN09', text: 'Viajantes constroem reputação; validações de quem tem confiança valem mais.' },
    ],
    creditBig: 'UFOP · BANCO DE DADOS II',
    creditText: 'Construído como trabalho prático: uma demonstração full-stack de modelagem em grafo, Cypher, consultas espaciais e otimização de rotas — embrulhada num almanaque de estrada.',
  },

  distilleries: {
    title: ['Cada alambique ', { em: 'no mapa.' }] as TitlePart[],
    lede: (n: number, live: boolean) =>
      `O catálogo por trás do grafo — ${n} alambiques em cidades reais de Minas Gerais, cada um pronto para entrar na sua rota. ${live ? '' : OFFLINE}`,
    suggestText: 'Conhece um alambique que não está aqui?',
    suggestCta: 'Indicar alambique',
    filterRegion: 'Região',
    filterCategory: 'Categoria',
    filterRating: 'Nota',
    rating45: '★ 4,5 ou mais',
    rating40: '★ 4,0 ou mais',
    filterTrust: 'Confiança (RN06)',
    includePending: 'Incluir “em validação”',
    searchLabel: (shown: number, total: number) => `Busca · ${shown} de ${total} exibidos`,
    searchPlaceholder: 'Nome, cidade ou região…',
    inValidation: 'em validação',
    since: (year: number) => ` · DESDE ${year}`,
    reviewsOne: 'NOTA DE CAMPO',
    reviewsMany: 'NOTAS DE CAMPO',
    addToRoute: 'ADICIONAR À ROTA →',
    prev: '← ANTERIOR',
    next: 'PRÓXIMA →',
    pageOf: (page: number, total: number) => `PÁGINA ${page} DE ${total}`,
    emptyText: 'Nada combina com esses filtros. Afrouxe um deles e tente de novo.',
  },

  journal: {
    title: ['Notas de ', { em: 'estrada.' }] as TitlePart[],
    lede: (live: boolean) => `Notas de campo registradas pelos viajantes depois de cada visita — a memória viva do grafo. ${live ? '' : OFFLINE}`,
    writeHead: 'NOVA NOTA DE CAMPO',
    pickAlambique: 'ALAMBIQUE',
    titleLabel: 'Título',
    titlePlaceholder: 'Uma linha que resuma a visita',
    bodyLabel: 'A nota',
    bodyPlaceholder: 'O que você provou? Quem serviu? O que o próximo viajante precisa saber?',
    ratingLabel: 'NOTA',
    pickError: 'Escolha o alambique desta nota.',
    done: 'NOTA REGISTRADA — OBRIGADO, VIAJANTE.',
    submit: 'Registrar nota',
    submitting: 'Registrando…',
    gateApiTitle: 'A API está fora do ar.',
    gateApiText: 'Suba o backend (`make back`) para registrar novas notas no grafo.',
    gateAuthTitle: 'Carregue seu próprio caderno.',
    gateAuthText: 'Entre na conta para registrar notas de campo, dar nota aos alambiques e construir uma reputação em que outros viajantes confiam.',
  },

  suggest: {
    title: ['Finque o pino, ', { em: 'conte o causo.' }] as TitlePart[],
    lede: 'Clique no mapa exatamente onde fica o alambique, preencha a ficha e envie. A indicação entra no grafo como EM VALIDAÇÃO até a comunidade confirmar (RN04 / RN05).',
    gateTitle: 'Só viajantes identificados indicam paradas.',
    gateText: 'Entre na sua conta (ou crie uma) para marcar o ponto no mapa e enviar a indicação.',
    needPin: 'Marque o ponto no mapa — clique onde fica o alambique.',
    mapHeadLeft: 'FIG. 04 — APONTE O LUGAR',
    mapPinned: 'PONTO MARCADO ✛',
    mapClick: 'CLIQUE NO MAPA',
    coords: (c: string) => `COORDENADAS ${c}`,
    waitingPin: 'AGUARDANDO PONTO…',
    tiles: 'TILES © OPENSTREETMAP · CARTO',
    formHead: 'FICHA DE INDICAÇÃO',
    nameLabel: 'Nome do alambique',
    namePlaceholder: 'Alambique do Serjão',
    cityLabel: 'Cidade',
    cityPlaceholder: 'Ouro Preto',
    categoryLabel: 'CATEGORIA',
    coordsLabel: 'Coordenadas (clique no mapa)',
    submit: 'Enviar indicação',
    submitting: 'Enviando…',
    note: 'A indicação fica visível no catálogo com o selo “em validação” até ser confirmada por outros viajantes ou pela curadoria.',
  },

  routePlanner: {
    title: ['A rota mais ', { em: 'rápida.' }] as TitlePart[],
    lede: 'Escolha os alambiques que quer visitar. O grafo parte do primeiro que você marcar, calcula a ordem de ida e volta que cobre todos rodando o mínimo de estrada — e desenha o trajeto sobre as rodovias reais do OpenStreetMap.',
    metricRoadKm: 'DISTÂNCIA RODOVIÁRIA',
    metricTotalKm: 'DISTÂNCIA TOTAL',
    metricTime: 'TEMPO DE VIAGEM',
    metricSaved: 'VOCÊ ECONOMIZA',
    metricStops: 'PARADAS NA ROTA',
    mapHeadLeft: (n: number) => `MAPA DE CAMPO · ${n} PARADAS`,
    mapTraced: 'ROTA TRAÇADA',
    mapPrompt: 'TOQUE NOS PINOS PARA MONTAR A VIAGEM',
    mapFootLeft: (live: boolean, nodes: number) => `${live ? 'GRAFO NEO4J AO VIVO' : 'DADOS DE EXEMPLO OFFLINE'} · ${nodes} NÓS`,
    footOsrmPending: 'AJUSTANDO ÀS ESTRADAS (OSRM)…',
    footOsrm: 'ESTRADAS REAIS · OSRM',
    footStraight: 'TRAÇADO EM LINHA RETA — — —',
    footTiles: 'TILES © OPENSTREETMAP · CARTO',
    stopsLabel: 'Paradas do roteiro',
    selectedCount: (n: number) => `${n} selecionadas`,
    partidaSuffix: ' · PARTIDA',
    startNote: 'O primeiro alambique marcado vira o ponto de partida — e a rota volta a ele no fim (ida e volta), pela ordem mais curta.',
    solve: 'Traçar a rota',
    solving: 'Calculando…',
    needTwo: 'Selecione ao menos dois alambiques para traçar.',
    itinTitle: 'Roteiro',
    twoOpt: 'TWO-OPT',
    nearest: 'VIZINHO MAIS PRÓXIMO',
    partida: 'PARTIDA',
    saida: 'saída',
    returnLabel: 'RETORNO À PARTIDA',
    itinNote: 'As distâncias por trecho são estimativas do grafo (geodésica × fator rodoviário 1,27).',
    itinNoteOsrm: ' Os totais acima seguem as estradas reais via OSRM.',
    emptyText: 'Escolha pelo menos dois alambiques — no mapa ou na lista — e trace a rota para ver a ordem de visita.',
    circuitsShow: 'Ver circuitos (HP-MOCD)',
    circuitsHide: 'Ocultar circuitos',
    circuitsLoading: 'Detectando circuitos…',
    circuitsNote: (n: number) => `${n} circuitos detectados por comunidades no grafo de proximidade (HP-MOCD). Alambiques com anel da mesma cor formam um circuito natural de visita.`,
    circuitsError: 'Não foi possível detectar os circuitos agora. O serviço de comunidades está no ar?',
  },

  gate: {
    enter: 'Entrar',
    create: 'Criar conta',
  },

  map: {
    draftPinTip: 'novo alambique aqui',
  },

  crumbGuia: 'Guia',
};
